name: mindeaseai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.1.0

  # Supabase
  supabase_flutter: ^2.5.1

  # Storage & permissions
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

  # Date & time
  intl: ^0.19.0

  # Speech
  speech_to_text: 7.3.0

  # Location (for mental health support redirect)
  geolocator: ^11.0.0

  # Open Google Maps / external apps
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true